---
- hosts: rchin11
  user: student
  become: yes

  vars:
    seneca_id: rchin11
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
    ssh_pub_key_path: "/home/{{ seneca_id }}/.ssh/id_rsa.pub"

  tasks:
    - name: Ensure Apache is updated
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create new user with sudo access
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        append: yes
        shell: /bin/bash
        create_home: yes

    - name: Allow user to run sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ seneca_id }} '
        line: '{{ seneca_id }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: Configure SSH public key for the user
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ lookup('file', ssh_pub_key_path) }}"

    - name: Create lab directory structure
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1, 9) | list }}"

